const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText,f);
const {applySale}=require('../lib/sales.ts');
const {fixedPackPrice}=require('../lib/packs.ts');
const {products}=require('../lib/catalog.ts');
const base={...products[0],price:3500,regularPrice:9900,packPrices:{3:9450,5:null,10:28000},sale:{enabled:true,percentOff:10,starts:'2026-09-20T00:00:00Z',ends:'2026-09-21T00:00:00Z'}};
const start=Date.parse(base.sale.starts),end=Date.parse(base.sale.ends);
assert.equal(applySale(base,start-1).price,3500);
const active=applySale(base,start);
assert.equal(active.price,3150);
assert.equal(fixedPackPrice(active,3),8505);
assert.equal(fixedPackPrice(active,5),13387);
assert.equal(fixedPackPrice(active,10),25200);
assert.deepEqual(applySale(active,start+1),active,'Never compound a sale');
assert.equal(applySale(active,end).price,3500);
assert.equal(fixedPackPrice(applySale(active,end),3),9450);
assert(!applySale(active,end).activeSale);
assert.equal(applySale({...base,sale:{...base.sale,enabled:false}},start).price,3500);
assert.equal(applySale({...base,sale:{...base.sale,ends:'invalid'}},start).price,3500);
assert.equal(applySale({...base,sale:null},start).price,3500);
assert.equal(base.price,3500,'Keep original catalog unchanged');
console.log('PASS: sale boundaries, expiry, disabled/invalid offers, no compounding, pack prices and source immutability');
