'use client';
import { useState } from 'react';
import { FileText, ArrowUpRight, Copy, QrCode, Download } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableBody, TableRow, TableHead, TableHeader, TableCell } from '@/components/ui/table';
import { coaOnRequest, coaRequestNotice, batchFor, batchStatus, batchStatusLabel, certificateFor, reportedResult, batchPath } from '@/lib/testing';
import { Product, compound, productFormat } from '@/lib/catalog';
import { Choice } from './primitives';
import { report } from './provider';
import { toast } from 'sonner';
export function CertificateButton({record:r}:{record:any}){
 const d=certificateFor(r);const [open,setOpen]=useState(false);const [page,setPage]=useState(1);const [zoom,setZoom]=useState('100');if(coaOnRequest(r))return <div className="coa-request" style={{flexBasis:'100%'}}><p style={{marginBottom:12}}>{coaRequestNotice}</p><a className="editorial-link" href={'/contact?subject='+encodeURIComponent('COA request: '+r.product_name+' / '+(r.product_lot||'current lot'))}>Request COA <ArrowUpRight size={16}/></a></div>;if(!d)return null;
 return <><button className="document-button" onClick={()=>setOpen(true)}><FileText size={18}/>Read original certificate <ArrowUpRight size={16}/></button><a href={d.url} target="_blank" rel="noopener noreferrer">Open original PDF <ArrowUpRight size={16}/></a><Dialog open={open} onOpenChange={setOpen}><DialogContent className="coa-dialog"><DialogTitle>{r.product_name} · Original certificate</DialogTitle><DialogDescription>Certificate lot: {d.batch_number||'Not listed'}. {d.report_date?'Reported '+d.report_date:d.release_date?'Released '+d.release_date:''}</DialogDescription>{batchStatus(r)!=='matched'&&<p className="notice error">The listed product lot is {r.product_lot||'not provided'}. This certificate identifies {d.batch_number||'a different or unspecified lot'}. Its results do not verify the listed product lot.</p>}<div className="document-actions"><label>Page <input aria-label="PDF page" type="number" min={1} value={page} onChange={e=>setPage(Math.max(1,Number(e.target.value)||1))}/></label><Choice label="PDF zoom" value={zoom} onChange={setZoom} options={[["75","75%"],["100","100%"],["125","125%"],["150","150%"]]}/><a href={d.url} target="_blank" rel="noopener noreferrer">Open / download PDF <ArrowUpRight size={16}/></a></div><iframe className="pdf-view" key={page+zoom} src={d.url+'#page='+page+'&zoom='+zoom} title={r.product_name+' certificate'}/><details><summary>Read extracted results and methods</summary><div className="document-results"><Table><TableHeader><TableRow><TableHead>Test</TableHead><TableHead>Reported result</TableHead><TableHead>Method</TableHead></TableRow></TableHeader><TableBody>{d.results.map((v:any,i:number)=><TableRow key={i}><TableCell>{v.analyte}</TableCell><TableCell>{v.result}{v.unit&&!v.result.includes(v.unit)?' '+v.unit:''}</TableCell><TableCell>{v.method||'Not reported'}</TableCell></TableRow>)}</TableBody></Table></div></details><p className="muted">If the embedded document does not load, use the original PDF link.</p></DialogContent></Dialog></>;
}
export function BatchDetails({record:r}:{record:any}){
 const d=certificateFor(r),matched=Boolean(d)&&r.lot_match==='matches';const [qr,setQr]=useState(''),[qrOpen,setQrOpen]=useState(false),[qrBusy,setQrBusy]=useState(false);
 const url=()=>window.location.origin+batchPath(r);
 async function makeQr(){setQrBusy(true);try{const code=await import('qrcode');setQr(await code.toDataURL(url(),{width:360,margin:4,errorCorrectionLevel:'M',color:{dark:'#242220',light:'#ffffff'}}));setQrOpen(true);}catch(e){report(e);}finally{setQrBusy(false);}}
 if(coaOnRequest(r))return <div className="batch-details"><div className="batch-facts"><dl><dt>Listed product lot</dt><dd>{r.product_lot||'Confirm current lot before purchase'}</dd></dl></div><div className="batch-actions"><CertificateButton record={r}/></div></div>;
 return <div className="batch-details"><div className="batch-facts"><dl><dt>Listed product lot</dt><dd>{r.product_lot||'Not listed'}</dd></dl><dl><dt>Certificate lot</dt><dd>{r.certificate_lot||'Not listed'}</dd></dl><dl><dt>Report date</dt><dd>{d?.report_date||d?.release_date||d?.issue_date||'Not reported'}</dd></dl><dl><dt>Purity</dt><dd>{matched?reportedResult(d,'purity'):'Not verified for this lot'}</dd></dl><dl><dt>Measured content</dt><dd>{matched?reportedResult(d,'assay'):'Not verified for this lot'}</dd></dl><dl><dt>Report reference</dt><dd>{d?.report_id||'Not reported'}</dd></dl></div>{!matched&&!coaOnRequest(r)&&<p className="batch-explanation">{d?'The available certificate identifies a different lot. Contact Biomod for the certificate matching this product.':'An original certificate for this listed lot is not available in the published documents yet.'}</p>}<div className="batch-actions"><CertificateButton record={r}/><button className="text-button" onClick={()=>navigator.clipboard.writeText(url()).then(()=>toast.success('Batch record link copied.')).catch(report)}><Copy size={16}/>Copy record link</button><button className="text-button" disabled={qrBusy} onClick={makeQr}><QrCode size={16}/>{qrBusy?'Creating code…':'QR code'}</button><a href={'/contact?subject='+encodeURIComponent('Documentation: '+r.product_name+' / '+(r.product_lot||'lot not listed'))}>Ask about this lot <ArrowUpRight size={16}/></a></div><Dialog open={qrOpen} onOpenChange={setQrOpen}><DialogContent className="qr-dialog"><DialogTitle>{r.product_name} · Batch record</DialogTitle><DialogDescription>Scan to open this published record. Lot: {r.product_lot||'Not listed'}. Access follows the site’s sharing settings.</DialogDescription>{qr&&<img src={qr} alt={'QR code for '+r.product_name+' batch record'} width={280} height={280}/>}<a className="button button-dark" href={qr} download={'biomod-'+r.record_id+'-qr-v1.png'}><Download size={17}/>Download QR code</a></DialogContent></Dialog></div>;
}
export function BatchPassport({product:p}:{product:Product}){const r=batchFor(p.id);if(!r)return null;return <section className="batch-passport"><div className="batch-passport-heading"><div><h2>Product & batch record</h2><p>{compound(p)} · {productFormat(p)}</p></div><span className={'batch-status '+batchStatus(r)}>{batchStatusLabel(r)}</span></div><BatchDetails record={r}/><p className="batch-source-note">From Biomod’s published records, September 11, 2026. Confirm the lot supplied with your order.</p></section>}
