'use client';
import { useState, useMemo } from 'react';
import { Heart, Grid2X2, List, Plus, Minus, X, ArrowRight } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from '@/components/ui/collapsible';
import { Progress } from '@/components/ui/progress';
import { products as source, Product, categories, money, size, mass, imagePath, cas } from '@/lib/catalog';
import { useStore, report, api } from './provider';
import { Choice, Check, Blank } from './primitives';
import { toast } from 'sonner';
export function ProductCard({ product: p, onAdd, pack = false }: {
    product: Product;
    onAdd?: (p: Product) => void;
    pack?: boolean;
}) { const { store, add, wish, ready } = useStore(); const [busy, setBusy] = useState(false); return <article className="product-card"><a className="product-image" href={'/product/' + p.slug}><img src={imagePath(p)} alt={p.image.alt || p.name} width={480} height={480} loading="lazy"/></a><button className="wishlist-button" aria-label={(store.wishlist.includes(p.id) ? 'Remove ' : 'Save ') + p.name + ' to wishlist'} aria-pressed={store.wishlist.includes(p.id)} onClick={() => wish(p.id).catch(report)}><Heart size={20} fill={store.wishlist.includes(p.id) ? 'currentColor' : 'none'}/></button><div className="product-info"><p className="product-category">{p.categories[0]?.name}</p><h3><a href={'/product/' + p.slug}>{p.name}</a></h3><p className="product-size">{size(p) || 'Research supply'}</p><strong className="product-price">{money(p.price)}</strong>{mass(p) ? <small>{money(p.price / mass(p)!)} / mg</small> : <small>{p.inStock ? 'In stock' : 'Unavailable'}</small>}<button className="button button-dark" disabled={!p.inStock || !p.purchasable || busy || !ready} onClick={async () => { setBusy(true); try {
    if (onAdd)
        onAdd(p);
    else
        await add(p);
}
catch (e) {
    report(e);
}
finally {
    setBusy(false);
} }}>{busy ? 'Adding…' : !p.inStock ? 'Out of stock' : pack ? 'Add to pack' : 'Add to cart'}<Plus size={16}/></button></div></article>; }
export function PackOffers() { const { store } = useStore(); return <div className="pack-offers">{[3, 5, 10].map(n => <a href={'/multi-pack?size=' + n} key={n}><span>Build a {n}-pack</span><strong>{store.config.packDiscounts[n] != null ? `Save ${store.config.packDiscounts[n]}%` : 'Choose your peptides'}</strong><ArrowRight size={22}/></a>)}</div>; }
export function Shop({ search = '' }: {
    search?: string;
}) { const { store } = useStore(); const [q, setQ] = useState(search); const [cats, setCats] = useState<string[]>([]); const [availability, setAvailability] = useState('all'); const [strength, setStrength] = useState('all'); const [sort, setSort] = useState('name'); const [min, setMin] = useState(''); const [max, setMax] = useState(''); const [list, setList] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const filtered = useMemo(() => store.products.filter(p => (!cats.length || p.categories.some(c => cats.includes(c.slug))) && (availability === 'all' || p.inStock === (availability === 'in')) && (strength === 'all' || size(p) === strength) && (!q || (p.name + ' ' + p.description + ' ' + p.sku).toLowerCase().includes(q.toLowerCase())) && (!min || p.price >= Number(min) * 100) && (!max || p.price <= Number(max) * 100)).sort((a, b) => sort === 'price-up' ? a.price - b.price : sort === 'price-down' ? b.price - a.price : sort === 'mg' ? (a.price / (mass(a) || 0.00001)) - (b.price / (mass(b) || 0.00001)) : sort === 'name-down' ? b.name.localeCompare(a.name) : a.name.localeCompare(b.name)), [store.products, cats, availability, strength, q, min, max, sort]); const toggle = (c: string) => setCats(cats.includes(c) ? cats.filter(v => v !== c) : [...cats, c]); return <><div className="page-heading"><h1>Shop All Products</h1><p>Research peptides, softgels, sprays, and supplies.</p></div><PackOffers /><div className="shop-layout"><Collapsible open={filtersOpen} onOpenChange={setFiltersOpen} asChild><aside className="filters"><h2>Filter Products</h2><label className="field">Search products<input value={q} onChange={e => setQ(e.target.value)} placeholder="Name, compound, or SKU"/></label><CollapsibleTrigger className="filter-trigger">{filtersOpen ? "Hide filters" : "Filter products"}</CollapsibleTrigger><CollapsibleContent forceMount className="filter-content"><Accordion type="multiple" defaultValue={['availability', 'categories', 'strength', 'price']}>{[['availability', 'Availability'], ['categories', 'Categories'], ['strength', 'Strength / size'], ['price', 'Price']].map(([v, t]) => <AccordionItem value={v} key={v}><AccordionTrigger>{t}</AccordionTrigger><AccordionContent>{v === 'availability' ? <Choice label="Availability" value={availability} onChange={setAvailability} options={[['all', 'All products'], ['in', `In stock (${store.products.filter(p => p.inStock).length})`], ['out', 'Out of stock']]}/> : v === 'categories' ? categories.map(c => <Check key={c.slug} checked={cats.includes(c.slug)} onChange={() => toggle(c.slug)}>{c.name} <small>({store.products.filter(p => p.categories.some(v => v.slug === c.slug)).length})</small></Check>) : v === 'strength' ? <Choice label="Strength or size" value={strength} onChange={setStrength} options={[["all", "All strengths / sizes"], ...[...new Set(store.products.map(size).filter(Boolean))].sort().map(v => [v, v] as [
        string,
        string
    ])]}/> : <div className="price-range"><input type="number" aria-label="Minimum price" min="0" value={min} onChange={e => setMin(e.target.value)} placeholder="$ Min"/><span>to</span><input type="number" min="0" aria-label="Maximum price" value={max} onChange={e => setMax(e.target.value)} placeholder="$ Max"/></div>}</AccordionContent></AccordionItem>)}</Accordion><button className="text-button" onClick={() => { setQ(''); setCats([]); setAvailability('all'); setStrength('all'); setMin(''); setMax(''); }}>Clear filters</button></CollapsibleContent></aside></Collapsible><div><div className="catalog-toolbar"><span aria-live="polite">{filtered.length} products</span><Choice label="Sort products" value={sort} onChange={setSort} options={[["name", "Name: A–Z"], ["name-down", "Name: Z–A"], ["price-up", "Price: low to high"], ["price-down", "Price: high to low"], ["mg", "Price per mg"]]}/><div className="view-toggle"><button aria-label="Grid view" aria-pressed={!list} onClick={() => setList(false)}><Grid2X2 size={19}/></button><button aria-label="List view" aria-pressed={list} onClick={() => setList(true)}><List size={19}/></button></div></div>{filtered.length ? <div className={'product-grid ' + (list ? 'product-list' : '')}>{filtered.map(p => <ProductCard key={p.id} product={p}/>)}</div> : <Blank title="No products match these filters.">Try another search or clear your filters.</Blank>}</div></div></>; }
export function ProductPage({ slug }: {
    slug: string;
}) { const { store, add } = useStore(); const [quantity, setQuantity] = useState(1); const [busy, setBusy] = useState(false); const p = store.products.find(p => p.slug === slug); if (!p)
    return <Blank title="Product not found."><a href="/shop">Return to the catalog</a></Blank>; return <><p className="breadcrumbs"><a href="/shop">Shop</a> / {p.categories[0]?.name} / {p.name}</p><div className="product-detail"><div className="detail-image"><img src={imagePath(p)} alt={p.image.alt || p.name}/></div><div className="detail-copy"><p className="product-category">{p.categories[0]?.name}</p><h1>{p.name}</h1><p className="detail-size">{size(p)}</p><p className="muted">SKU: {p.sku || 'Not provided'}</p><p className="detail-price">{money(p.price)}</p>{mass(p) && <p>{money(p.price / mass(p)!)} per mg</p>}<p className={p.inStock ? 'stock' : 'muted'}>{p.inStock ? 'In stock' : 'Out of stock'}</p><p>{p.description.split('\n').find(s => s.trim().length > 50)?.slice(0, 260)}</p><a className="coa-link" href={'/testing?product=' + p.id}>View testing documentation <ArrowRight size={17}/></a><div className="add-row"><div className="quantity"><button aria-label="Decrease quantity" disabled={quantity <= 1} onClick={() => setQuantity(quantity - 1)}><Minus size={16}/></button><input aria-label="Quantity" type="number" min="1" max={p.maxQuantity || 100} value={quantity} onChange={e => setQuantity(Math.max(1, Math.min(p.maxQuantity || 100, Number(e.target.value) || 1)))}/><button aria-label="Increase quantity" disabled={quantity >= (p.maxQuantity || 100)} onClick={() => setQuantity(quantity + 1)}><Plus size={16}/></button></div><button className="button button-gold" disabled={busy || !p.inStock} onClick={async () => { setBusy(true); try {
    await add(p, quantity);
}
catch (e) {
    report(e);
}
finally {
    setBusy(false);
} }}>{busy ? 'Adding…' : 'Add to cart'}</button></div>{!p.inStock && <button className="text-button" onClick={() => api('notify', { id: p.id }).then(d => toast.success(d.message)).catch(report)}>Request a restock notification</button>}<div className="research-note"><strong>For laboratory research use only.</strong><p>Not for human or animal use. Available to customers age 21 and older.</p></div><p className="muted">Free standard U.S. shipping on orders of $200 or more.</p></div></div><Tabs defaultValue="description" className="product-tabs"><TabsList><TabsTrigger value="description">Description</TabsTrigger><TabsTrigger value="specifications">Specifications</TabsTrigger><TabsTrigger value="shipping">Shipping</TabsTrigger></TabsList><TabsContent value="description"><div className="prose preserve-lines">{p.description}</div></TabsContent><TabsContent value="specifications"><dl className="specs"><dt>Product</dt><dd>{p.name}</dd><dt>Size</dt><dd>{size(p) || 'See product label'}</dd><dt>SKU</dt><dd>{p.sku || 'Not provided'}</dd><dt>CAS</dt><dd>{cas(p) || 'See product documentation'}</dd><dt>Use</dt><dd>Laboratory research only</dd></dl></TabsContent><TabsContent value="shipping"><p>U.S. delivery only. Weekday orders placed before 2 p.m. Pacific normally process the same business day, excluding federal holidays. Order review may extend processing.</p><a href="/shipping-policy">Read the shipping policy</a></TabsContent></Tabs><section className="related"><h2>Explore the catalog</h2><div className="product-grid">{store.products.filter(v => v.id !== p.id && v.categories[0]?.slug === p.categories[0]?.slug).slice(0, 3).map(v => <ProductCard key={v.id} product={v}/>)}</div></section></>; }
export function PackBuilder({ initialSize = 3 }: {
    initialSize?: number;
}) { const { store, saveCart, ready } = useStore(); const [count, setCount] = useState([3, 5, 10].includes(initialSize) ? initialSize : 3); const [selected, setSelected] = useState<number[]>([]); const [q, setQ] = useState(''); const [busy, setBusy] = useState(false); const ps = store.products.filter(p => p.categories.some(c => c.slug === 'research-peptides') && p.inStock && p.name.toLowerCase().includes(q.toLowerCase())); const total = selected.reduce((s, id) => s + (store.products.find(p => p.id === id)?.price || 0), 0); const percent = store.config.packDiscounts[count]; const savings = Math.round(total * (percent || 0) / 100); return <><div className="page-heading"><h1>Build Your Pack</h1><p>Choose any {count} research peptides from the available catalog.</p></div><div className="pack-builder"><aside className="pack-summary"><h2>Your research pack</h2><Choice label="Pack size" value={String(count)} onChange={v => { setCount(Number(v)); setSelected(selected.slice(0, Number(v))); }} options={[["3", "3 products"], ["5", "5 products"], ["10", "10 products"]]}/><p>{selected.length} of {count} selected</p><Progress value={selected.length / count * 100}/><div className="pack-slots">{Array.from({ length: count }, (_, i) => { const p = store.products.find(p => p.id === selected[i]); return <div className={'pack-slot ' + (p ? 'filled' : '')} key={i}>{p ? <><img src={imagePath(p)} alt=""/><span>{p.name}<small>{size(p)}</small></span><button aria-label={'Remove ' + p.name + ' from pack'} onClick={() => setSelected(selected.filter((_, j) => i !== j))}><X size={17}/></button></> : <><span>{i + 1}</span><span>Select a peptide</span></>}</div>; })}</div><div className="summary-lines"><p><span>Subtotal</span><strong>{money(total)}</strong></p>{percent !== null && percent !== undefined && <p><span>Pack savings ({percent}%)</span><strong>−{money(savings)}</strong></p>}<p className="total"><span>Total</span><strong>{money(total - savings)}</strong></p></div><button className="button button-gold" disabled={selected.length !== count || busy || !ready} onClick={async () => { setBusy(true); try {
    const packId = crypto.randomUUID();
    await saveCart([...store.cart, ...selected.map(id => ({ id, quantity: 1, packId, packSize: count }))]);
    setSelected([]);
    toast.success('Your pack has been added to the cart', { action: { label: 'View cart', onClick: () => location.assign('/cart') } });
}
catch (e) {
    report(e);
}
finally {
    setBusy(false);
} }}>{busy ? 'Adding…' : selected.length === count ? 'Add pack to cart' : `Select ${count - selected.length} more`}</button><button className="text-button" disabled={!selected.length} onClick={() => setSelected([])}>Clear pack</button></aside><div><label className="field pack-search">Search peptides<input value={q} onChange={e => setQ(e.target.value)} placeholder="Find a peptide"/></label><div className="product-grid">{ps.map(p => <ProductCard key={p.id} product={p} pack onAdd={v => { if (selected.length >= count) {
    toast.error('Your pack is complete. Remove an item to change it.');
    return;
} const used = selected.filter(id => id === v.id).length; if (used >= (v.stockQuantity ?? v.maxQuantity ?? 100)) {
    toast.error('This quantity is not available.');
    return;
} setSelected([...selected, v.id]); }}/>)}</div>{!ps.length && <Blank title="No peptides found.">Try another product name.</Blank>}</div></div></>; }
export function Presales() { const { store, add } = useStore(); const now = Date.now(); return <><div className="page-heading"><h1>Presales</h1><p>Upcoming releases and advance ordering.</p></div>{!store.config.presalesEnabled || !store.campaigns.length ? <Blank title="No presales are open right now."><p>Released products are available in our regular catalog.</p><a className="button button-dark" href="/shop">Shop products</a></Blank> : store.campaigns.map(c => <section className="presale" key={c.id}><h2>{c.title}</h2><p>{now < Date.parse(c.starts) ? 'Opens ' + new Date(c.starts).toLocaleString() : now > Date.parse(c.ends) ? 'Closed' : 'Open until ' + new Date(c.ends).toLocaleString()}</p><p>Expected shipping: {c.ships}. Limit {c.maxPerCustomer} per customer.</p><p>Presale items must be purchased separately from in-stock products.</p><div className="product-grid">{store.products.filter(p => c.productIds.includes(p.id)).map(p => <ProductCard key={p.id} product={p} onAdd={() => { if (now < Date.parse(c.starts) || now > Date.parse(c.ends))
    toast.error('This presale is not currently open.');
else
    add(p, 1, c.id).catch(report); }}/>)}</div></section>)}</>; }
