'use client';
import { ProductImage } from './product-image';
import { useState, useId } from 'react';
import { X, ArrowUpRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Product, compound, productFormat, money, mass } from '@/lib/catalog';
import { packSizes, fixedPackPrice, packUnit, packContents, supportsPacks, packUnitLimit } from '@/lib/packs';
import { batchFor, batchStatusLabel } from '@/lib/testing';
import { useStore, report } from './provider';
export function ProductComparison({products,open,onOpenChange,onRemove}:{products:Product[];open:boolean;onOpenChange:(v:boolean)=>void;onRemove:(id:number)=>void}){
 const [count,setCount]=useState(1);const [busy,setBusy]=useState<number|null>(null);const id=useId();const {addFixedPack,add,ready}=useStore();
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="comparison-dialog"><DialogTitle>Compare your selection</DialogTitle><DialogDescription>Compare listed contents, format, documentation, and price. Different formulations are not interchangeable.</DialogDescription><RadioGroup className="comparison-size" aria-label="Compare pack size" value={String(count)} onValueChange={v=>setCount(Number(v))}>{packSizes.map(n=><label key={n} htmlFor={id+n}><RadioGroupItem id={id+n} value={String(n)}/>{n===1?'Single':n+'-pack'}</label>)}</RadioGroup><p className="comparison-scroll-note">Scroll sideways to see every product.</p><div className="comparison-scroll"><div className="comparison-grid" style={{gridTemplateColumns:`repeat(${Math.max(products.length,1)},minmax(235px,1fr))`}}>{products.map(p=>{const eligible=supportsPacks(p),n=eligible?count:1,price=eligible?fixedPackPrice(p,n):p.price;return <article className="comparison-product" key={p.id}><button className="icon-button" aria-label={'Remove '+p.name+' from comparison'} onClick={()=>onRemove(p.id)}><X size={18}/></button><ProductImage product={p}/><h3>{p.name}</h3><div><small>Compound</small><p>{compound(p)}</p></div><div><small>Format / contents</small><p>{productFormat(p)} · {packContents(p)}</p></div><div><small>Batch documentation</small><a href={'/testing?product='+p.id}>{batchStatusLabel(batchFor(p.id))} <ArrowUpRight size={14}/></a></div><div><small>{n===1?'Single product':n+'-pack'} total</small><strong>{money(price)}</strong><p>{money(price/n)} / {packUnit(p)}{mass(p)?' · '+money(price/(n*mass(p)!))+' / mg':''}</p></div><button className="button button-dark" disabled={busy!==null||!ready||!p.inStock||!p.purchasable||n>packUnitLimit(p)} onClick={async()=>{setBusy(p.id);try{if(eligible)await addFixedPack(p,n);else await add(p);}catch(e){report(e);}finally{setBusy(null);}}}>{busy===p.id?'Adding…':!p.inStock?'Unavailable':n===1?'Add to cart':'Add '+n+'-pack'}</button></article>})}</div></div></DialogContent></Dialog>;
}
