'use client';
import { AboutBrand, TrademarkNote } from './brand-story';
import { QualityGuide } from './quality-guide';
import { ResearchFAQ } from './research-faq';
import { useState, FormEvent } from 'react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Field, formData } from './primitives';
import { api, report } from './provider';
import { toast } from 'sonner';
export const faqs = [['Who can purchase Biomod products?', 'Products are available to adults age 21 and older for laboratory, analytical, and scientific research. They are not for human or animal use.'], ['Where can I find a Certificate of Analysis?', 'Open Testing Results and select a product. Available certificates identify their own batch, methods, and results. Pending documentation is shown as pending. Always compare the certificate lot with the product lot.'], ['Where does Biomod ship?', 'Biomod ships within the United States. Standard shipping is free on orders of $200 or more after discounts and before tax.'], ['When will my order be processed?', 'Weekday orders placed before 2 p.m. Pacific normally process the same business day, excluding federal holidays. Orders placed later normally process the next business day. Order review may extend processing.'], ['Can you provide dosing or medical advice?', 'No. Biomod supplies products for research and does not provide dosing, treatment, or medical guidance.'], ['What if my order is damaged or incorrect?', 'Contact contact@trybiomod.com within 48 hours of delivery with your order number and photos of the product and packaging. Read the Returns & Refunds policy for details.']];
export function FAQ() { return <Accordion type="single" collapsible className="faq-list">{faqs.map(([q, a], i) => <AccordionItem key={i} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion>; }
export function Contact({subject=''}:{subject?:string}) { const [busy, setBusy] = useState(false); const [sent, setSent] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); try {
    const d = await api('contact', formData(e.currentTarget));
    toast.success(d.message);
    setSent(true);
}
catch (e) {
    report(e);
}
finally {
    setBusy(false);
} } return <><div className="page-heading"><h1>Contact Us</h1><p>Product documentation, orders, and general questions.</p></div><div className="contact-layout"><div><h2>Get in touch</h2><a href="mailto:contact@trybiomod.com">contact@trybiomod.com</a><p>For order questions, include your order number. Please do not send payment details or personal medical information.</p><p>Biomod does not offer dosing or medical guidance.</p><a className="editorial-link" href="/locations">Locations and visiting details</a><br/><a href="/faq">Ordering and documentation questions</a></div>{sent ? <div className="notice"><h2>Message received</h2><p>Your message has been saved for the Biomod team.</p><button className="text-button" onClick={() => setSent(false)}>Write another message</button></div> : <form className="store-form" onSubmit={submit}><div className="form-row"><Field label="Name" name="name"/><Field label="Email" name="email" type="email"/></div><Field label="Subject" name="subject" defaultValue={subject}/><Field label="Message" name="message"><textarea name="message" rows={7} required maxLength={5000}/></Field><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button className="button button-dark" disabled={busy}>{busy ? 'Sending…' : 'Send message'}</button></form>}</div></>; }
const content: Record<string, {
    title: string;
    paragraphs: string[];
}> = {
    'about': { title: 'About Biomod', paragraphs: ['BIOMOD is a U.S. Marine Corps veteran-owned supplier of research products. Our catalog includes research compounds, softgels, sprays, aminos, and laboratory supplies.', 'Product pages list the compound, format and container size. The testing library links the original reports available for each product and identifies missing or mismatched documents.', 'All products are intended exclusively for laboratory, analytical, and scientific research. They are not intended for human or animal use.'] },
    'research-use-only': { title: 'Research Use Only', paragraphs: ['All Biomod products are supplied exclusively for laboratory, analytical, and scientific research by qualified adults age 21 and older.', 'Products are not for human or animal use, consumption, treatment, or diagnosis. Biomod does not provide dosing or medical advice.', 'By ordering, the purchaser confirms lawful research use and responsibility for appropriate facilities, handling, storage, and disposal.'] },
    'shipping-policy': { title: 'Shipping Policy', paragraphs: ['Biomod ships within the United States. Standard shipping is free on orders of $200 or more after discounts and before tax. Shipping and tax are shown for review before payment.', 'Weekday orders placed before 2 p.m. Pacific normally process the same business day, excluding federal holidays. Later orders normally process the next business day. Order review can extend processing.', 'Carrier delivery dates are estimates. Ensure the delivery address is complete and accurate before submitting an order. For delivery questions, contact contact@trybiomod.com with your order number.'] },
    'returns-refunds': { title: 'Returns & Refunds', paragraphs: ['Research product sales are generally final. Contact Biomod about damaged, incorrect, or missing items within 48 hours of delivery.', 'Include the order number and clear photos of the product, packaging, and shipping label. Preserve the product and packaging while the issue is reviewed.', 'Do not return research materials without instructions from Biomod. Any replacement or refund depends on review of the documented issue. Contact contact@trybiomod.com for assistance.'] },
    'terms-of-sale': { title: 'Terms of Sale', paragraphs: ['Purchasers must be at least 21 years old and purchase exclusively for laboratory research. Products are not intended for human or animal use.', 'Product availability, pricing, and order eligibility are validated before payment. An order is accepted only after payment verification and any required review.', 'Customers are responsible for accurate account and delivery information and for complying with applicable research, handling, and disposal requirements. Shipping and returns are governed by the corresponding policies.', 'These storefront terms are a review draft for the rebuilt site.'] },
    'privacy-policy': { title: 'Privacy Policy', paragraphs: ['This storefront uses account, contact, delivery, and order information to provide customer services and process requested purchases. Cart and wishlist cookies maintain your shopping session.', 'Card details are entered on the payment provider’s hosted page. The storefront does not collect or store raw card numbers.', 'Account information is handled by the connected account provider. Requests to access or correct your information can be sent to contact@trybiomod.com.', 'This policy is a review draft for the rebuilt site. Final provider, retention, and privacy terms must be confirmed before public launch.'] },
    'international-partners': { title: 'Partners', paragraphs: ['Interested in working with Biomod? Contact our team to discuss product documentation, research supply requirements, and partnership opportunities.', 'Biomod currently ships within the United States. International purchasing and distribution are not enabled in this storefront.'] },
};
export function ContentPage({ path }: {
    path: string;
}) { if (path === 'quality-standard') return <QualityGuide/>; if (path === 'about') return <AboutBrand/>; if (path === 'faq')
    return <ResearchFAQ/>; const c = content[path] || content.about; return <div className="content-page"><h1>{c.title}</h1><div className="prose">{c.paragraphs.map(p => <p key={p}>{p}</p>)}</div>{path === 'international-partners' ? <a className="button button-dark" href="/contact">Contact Biomod</a> : null}</div>; }
export function Footer() { return <footer className="site-footer"><div className="wrap footer-grid"><div><a href="/"><img src="/brand/logo-white-tm-v36.svg" alt="BIOMOD" width={210}/></a><p>U.S. Marine Corps veteran owned.</p><p>For laboratory research use only.<br />Not for human or animal use. Age 21+.</p><a href="mailto:contact@trybiomod.com">contact@trybiomod.com</a></div><div><h3>Shop & Account</h3><a href="/shop">All products</a><a href="/softgels">Our softgels</a><a href="/multi-pack">Build a Pack</a><a href="/presales">Presales</a><a href="/account">My account</a><a href="/account/affiliate">Affiliate program</a></div><div><h3>Research & Support</h3><a href="/testing">Testing results</a><a href="/quality-standard">How to read a COA</a><a href="/faq">FAQs</a><a href="/about">About Biomod</a><a href="/locations">Locations</a><a href="/contact">Contact us</a></div><div><h3>Policies</h3><a href="/research-use-only">Research use only</a><a href="/shipping-policy">Shipping policy</a><a href="/returns-refunds">Returns & refunds</a><a href="/terms-of-sale">Terms of sale</a><a href="/privacy-policy">Privacy policy</a></div></div><div className="wrap footer-brand"><TrademarkNote/></div><div className="wrap footer-bottom">© {new Date().getFullYear()} BIOMOD. All rights reserved.</div></footer>; }
