'use client';
import { ArrowUpRight } from 'lucide-react';
import { ProductCard } from './catalog';
import { useStore } from './provider';
import { TrademarkNote } from './brand-story';

const spotlight = [
  { name: 'BIONIC', slug: 'softgel-bionic-bpc-157-arginate-kpv-vitamin-e', identity: 'BPC-157 Arginate + KPV + Vitamin E', specification: 'Enteric-coated formulation', detail: 'An arginate form of BPC-157, combined with KPV and vitamin E. Supplied as 60 softgels.' },
  { name: 'LUMEN', slug: 'softgel-lumen-ghk-cu-ahk-cu-astaxanthin-vitamin-e', identity: 'GHK-Cu + AHK-Cu + Astaxanthin + Vitamin E', specification: 'Enteric-coated formulation', detail: 'Two copper research compounds in a four-component formula. Supplied as 60 softgels; confirm the astaxanthin quantity with our team.' },
  { name: 'DELTA', slug: 'softgel-delta-pinealon-epithalon', identity: 'Pinealon + Epitalon', specification: 'Enteric-coated formulation', detail: 'A two-compound combination in an enteric-coated softgel. Supplied as 30 softgels.' },
];

export function Softgels() {
  const { store } = useStore();
  const products = store.products.filter(product => product.categories.some(category => category.slug === 'softgels'));
  return <article className="softgel-story-page">
    <header className="softgel-story-hero"><div><h1>The Original<br/>Peptide Softgel<span className="trademark-symbol">™</span></h1><p>BIOMOD’s own formulations, developed around the softgel format. Manufactured in California, USA. Rooted in Las Vegas.</p><div className="softgel-collection-actions"><a className="button button-gold" href="#softgel-collection">Shop the softgel collection <ArrowUpRight size={18}/></a><a className="softgel-spray-link" href="/shop?category=spray-products">Shop nasal &amp; spray products <ArrowUpRight size={18}/></a></div></div><figure><img src="/brand/softgel-layers-v10.webp" alt="Conceptual cutaway of an enteric softgel: blue protection outside a silver gelatin shell and gold liquid fill. Illustrative colors; not to scale." width={1672} height={941} fetchPriority="high"/></figure></header>
    <div className="softgel-manufacturing"><strong>California softgel manufacturing</strong><span>cGMP standards</span><a href="/about">U.S. Marine Corps veteran owned <ArrowUpRight size={17}/></a></div>
    <section className="softgel-formulation-section"><div className="softgel-section-opening"><h2>The formulation<br/>comes first.</h2><p>A softgel is a format. The ingredients, shell and release specification make each formulation its own. These three products are the heart of our softgel story.</p></div><div className="softgel-formulation-grid">{spotlight.map(product => <article key={product.slug}><a href={'/product/' + product.slug}><img src={'/products/' + product.slug + '-bottle-v9.png'} alt={product.name + ' bottle illustration'} width={1254} height={1254} loading="lazy"/></a><h3>{product.name}</h3><p className="formula-identity">{product.identity}</p><p>{product.detail}</p><strong>{product.specification}</strong><a className="editorial-link" href={'/product/' + product.slug}>View {product.name} <ArrowUpRight size={17}/></a></article>)}</div></section>
    <section className="softgel-design"><div className="softgel-design-intro"><h2>Inside our<br/>softgel.</h2><p>BIONIC, LUMEN and DELTA combine a liquid fill, a gelatin shell and specified enteric protection. Each layer has a distinct job.</p></div><dl className="softgel-layer-key"><div><dt>Enteric protection <span>Blue in the illustration</span></dt><dd>Designed to delay release in acidic conditions and dissolve as the surrounding pH rises.</dd></div><div><dt>Gelatin shell <span>Silver in the illustration</span></dt><dd>The softgel enclosure surrounding the liquid formulation.</dd></div><div><dt>Liquid fill <span>Gold in the illustration</span></dt><dd>The listed compounds in a formulation that includes MCT oil and sunflower lecithin.</dd></div></dl><details className="softgel-science-note"><summary>What does an enteric specification tell you?</summary><div><p>An enteric specification describes how a formulation is designed to release its contents. Delayed release alone does not establish absorption or superiority over another product; those require testing of the finished formula.</p><a className="editorial-link" href="/testing">Review available batch documents <ArrowUpRight size={18}/></a><p className="softgel-science-source">General reference: <a href="https://www.evonik.com/en/applications/application_1993581/eudragit-functional-film-coating-polymers-for-solid-oral-dosage-forms/eudragit-functional-film-coating-polymers-for-delayed-release.html" target="_blank" rel="noreferrer">How enteric coatings work, Evonik</a>. This explains coating technology; it is not a BIOMOD product study or supplier statement.</p></div></details></section>
    <section className="softgel-full-collection" id="softgel-collection"><div className="section-intro"><h2>The BIOMOD softgel collection.</h2><p>Eight formulations. Full bottles in 1, 3, 5 and 10 packs.</p></div><div className="product-grid">{products.map(product => <ProductCard key={product.id} product={product}/>)}</div></section>
    <section className="softgel-origin-line"><h2>From our Las Vegas roots.</h2><p>A dedicated research compound storefront and a growing formulation business. Learn where BIOMOD began and meet the brand behind the softgels.</p><a className="editorial-link" href="/about">Our story <ArrowUpRight size={18}/></a></section><TrademarkNote/>
  </article>;
}
