'use client';
import { useState } from 'react';
import { FileText, ExternalLink, ArrowDownUp } from 'lucide-react';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import coas from '@/lib/coas-source-v1.json';
import { Choice, Blank } from './primitives';
const records = coas.records as any[];
const documents = coas.documents as any[];
const result = (d: any, kind: string) => d?.results?.filter((r: any) => r.kind === kind).map((r: any) => r.result).join('; ') || 'Not reported';
export function Testing({ product = '', lot = '' }: {
    product?: string;
    lot?: string;
}) { const [q, setQ] = useState(''); const [selected, setSelected] = useState(product || 'all'); const [status, setStatus] = useState('all'); const [sort, setSort] = useState('name'); const [doc, setDoc] = useState<any>(null); const [page, setPage] = useState(1); const [zoom, setZoom] = useState('100'); const focused = lot ? records.find(r => r.record_id === lot || r.product_lot === lot) : null; const rows = records.filter(r => (selected === 'all' || String(r.product_id) === selected) && (!focused || r.record_id === focused.record_id) && (status === 'all' || (status === 'pdf' ? r.has_certificate_pdf : !r.has_certificate_pdf)) && [r.product_name, r.public_identity, r.product_lot, r.certificate_lot].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase())).sort((a, b) => sort === 'lot' ? String(a.product_lot || '').localeCompare(String(b.product_lot || '')) : a.product_name.localeCompare(b.product_name)); const open = (d: any) => { setDoc(d); setPage(1); setZoom('100'); }; return <><div className="page-heading"><h1>Testing Results</h1><p>Review product lots and the original laboratory documents.</p></div><p className="testing-note">Results belong to the batch printed on each certificate. Where a product lot and certificate lot differ, confirm the correct document before purchase.</p><div className="testing-toolbar"><input aria-label="Search testing records" value={q} onChange={e => setQ(e.target.value)} placeholder="Search product, compound, or lot"/><Choice label="Filter testing by product" value={selected} onChange={setSelected} options={[["all", "All products"], ...records.map(r => [String(r.product_id), r.product_name] as [
        string,
        string
    ]).sort((a, b) => a[1].localeCompare(b[1]))]}/><Choice label="Document availability" value={status} onChange={setStatus} options={[["all", "All documentation"], ["pdf", "Certificate linked"], ["pending", "No certificate linked"]]}/></div><p className="muted" aria-live="polite">{rows.length} products · Updated from Biomod’s published documents on September 11, 2026</p>{!rows.length ? <Blank title="No testing records found.">Try another product or batch number.</Blank> : <Table className="testing-table"><TableHeader><TableRow><TableHead><button onClick={() => setSort('name')}>Product <ArrowDownUp size={14}/></button></TableHead><TableHead>Size / identity</TableHead><TableHead><button onClick={() => setSort('lot')}>Product lot <ArrowDownUp size={14}/></button></TableHead><TableHead>Certificate lot</TableHead><TableHead>Purity</TableHead><TableHead>Content assay</TableHead><TableHead>Documentation</TableHead></TableRow></TableHeader><TableBody>{rows.map(r => { const d = documents.find(d => d.document_id === r.document_id && d.is_certificate); const mismatch = r.lot_match === 'mismatch'; return <TableRow key={r.record_id}><TableCell><a href={'/product/' + r.product_slug}><strong>{r.product_name}</strong></a></TableCell><TableCell>{r.product_facts?.Size || r.public_identity || 'Not listed'}</TableCell><TableCell>{r.product_lot || 'Not listed'}</TableCell><TableCell>{r.certificate_lot || 'Not listed'}{mismatch && <small className="data-warning">Lot mismatch</small>}</TableCell><TableCell>{mismatch ? 'See linked certificate' : result(d, 'purity')}</TableCell><TableCell>{mismatch ? 'See linked certificate' : result(d, 'assay')}</TableCell><TableCell>{d ? <button className="coa-open" onClick={() => open({ ...d, productName: r.product_name, mismatch, productLot: r.product_lot })}><FileText size={18}/>View certificate</button> : <span>{r.coa_status === 'Active COA' ? 'Certificate unavailable' : r.coa_status || 'Pending documentation'}</span>}</TableCell></TableRow>; })}</TableBody></Table>}<Dialog open={Boolean(doc)} onOpenChange={v => { if (!v)
    setDoc(null); }}><DialogContent className="coa-dialog"><DialogTitle>{doc?.productName} · Certificate</DialogTitle><DialogDescription>Certificate batch: {doc?.batch_number || 'Not listed'}. {doc?.report_date ? 'Report date: ' + doc.report_date : doc?.release_date ? 'Release date: ' + doc.release_date : ''}</DialogDescription>{doc?.mismatch && <p className="notice error">The product lists lot {doc.productLot}; this certificate lists lot {doc.batch_number}. These results have not been assigned to the product lot.</p>}<div className="document-actions"><label>Page <input aria-label="PDF page" type="number" min="1" max={Math.max(...(doc?.results || []).map((r: any) => r.page || 1), 1)} value={page} onChange={e => setPage(Math.max(1, Number(e.target.value) || 1))}/></label><Choice label="PDF zoom" value={zoom} onChange={setZoom} options={[["75", "75%"], ["100", "100%"], ["125", "125%"], ["150", "150%"]]}/><a href={doc?.url} target="_blank" rel="noopener noreferrer">Open / download PDF <ExternalLink size={16}/></a></div>{doc && <iframe key={doc.document_id + page + zoom} className="pdf-view" src={doc.url + '#page=' + page + '&zoom=' + zoom} title={doc.productName + ' certificate'}/>}<p className="muted">If the preview is unavailable, open the original PDF above.</p><details><summary>Certificate results and methods</summary><div className="document-results"><Table><TableHeader><TableRow><TableHead>Test</TableHead><TableHead>Result as reported</TableHead><TableHead>Method</TableHead><TableHead>PDF page</TableHead></TableRow></TableHeader><TableBody>{doc?.results.map((r: any, i: number) => <TableRow key={i}><TableCell>{r.analyte}</TableCell><TableCell>{r.result}{r.unit && !r.result?.includes(r.unit) ? ' ' + r.unit : ''}</TableCell><TableCell>{r.method || 'Not reported'}</TableCell><TableCell>{r.page}</TableCell></TableRow>)}</TableBody></Table></div></details></DialogContent></Dialog></>; }
