'use client';
import { useState } from 'react';
import { ArrowUpRight, Search } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { batchRecords, batchStatus, batchStatusLabel } from '@/lib/testing';
import { compound, imagePath } from '@/lib/catalog';
import { useStore } from './provider';
import { Choice, Blank } from './primitives';
import { BatchDetails } from './batch-record';
export function Testing({product='',lot=''}:{product?:string;lot?:string}){
 const {store}=useStore();const [q,setQ]=useState('');const [selected,setSelected]=useState(product||'all');const [status,setStatus]=useState('all');
 const rows=batchRecords.filter(r=>(selected==='all'||String(r.product_id)===selected)&&(!lot||r.record_id===lot||r.product_lot===lot)&&(status==='all'||batchStatus(r)===status)&&[r.product_name,r.public_identity,r.product_lot,r.certificate_lot,compound(store.products.find(p=>p.id===r.product_id)!)].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()));
 return <><div className="testing-heading"><div className="page-heading"><h1>Batch documents</h1><p>Search product lots and read the original laboratory reports.</p></div><a className="editorial-link" href="/quality-standard">Understand the tests <ArrowUpRight size={18}/></a></div><div className="testing-counts">{[['all','Product records'],['matched','Matching-lot certificates'],['mismatch','Lots to confirm'],['pending','Documentation pending']].map(([v,t])=><button key={v} aria-pressed={status===v} onClick={()=>setStatus(v)}><strong>{batchRecords.filter(r=>v==='all'||batchStatus(r)===v).length}</strong><span>{t}</span></button>)}</div><div className="testing-toolbar"><div className="record-search"><Search size={19}/><input aria-label="Search testing records" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product, compound, or lot"/></div><Choice label="Filter testing by product" value={selected} onChange={setSelected} options={[["all","All products"],...batchRecords.map(r=>[String(r.product_id),r.product_name] as [string,string]).sort((a,b)=>a[1].localeCompare(b[1]))]}/><Choice label="Document availability" value={status} onChange={setStatus} options={[["all","All documentation"],["matched","Matching-lot certificate"],["mismatch","Lot needs confirmation"],["pending","Documentation pending"]]}/></div><div className="record-results"><p aria-live="polite">{rows.length} product {rows.length===1?'record':'records'}</p>{(q||status!=='all'||selected!=='all'||lot)&&<a href="/testing">Clear all filters</a>}<span>Source records updated September 11, 2026</span></div>{!rows.length?<Blank title="No batch records found.">Try another product or lot number.</Blank>:<Accordion type="multiple" defaultValue={product||lot?rows.map(r=>r.record_id):[]} className="batch-records">{rows.map(r=>{const p=store.products.find(p=>p.id===r.product_id);return <AccordionItem key={r.record_id} value={r.record_id}><AccordionTrigger className="batch-record-trigger"><span className="batch-product">{p&&<img src={imagePath(p)} alt="" width={65} height={65}/>}<span><strong>{r.product_name}</strong><small>{p?compound(p):r.public_identity}</small></span></span><span className="batch-listed-lot"><small>Listed lot</small>{r.product_lot||'Not listed'}</span><span className={'batch-status '+batchStatus(r)}>{batchStatusLabel(r)}</span></AccordionTrigger><AccordionContent><BatchDetails record={r}/><a className="editorial-link" href={'/product/'+r.product_slug}>View product <ArrowUpRight size={16}/></a></AccordionContent></AccordionItem>})}</Accordion>}<p className="testing-footnote">A matching lot number links a document to the listed batch. Read the original report for test scope, methods, measured values, and limitations. Pending documentation is not a completed test.</p></>;
}
